"""Common backend interface – every backend must implement ProxyBackend."""
from typing import Dict, List, Protocol

class ProxyBackend(Protocol):
    """Abstract reverse-proxy backend API."""

    def apply_rules(self, rules: Dict[str, List[str]]) -> None: ...
    def add_rule(self, service: str, line: str) -> None: ...
    def remove_rule(self, service: str, line: str) -> None: ...
    def reload(self) -> None: ...
