# Dockerfile.prod
FROM python:3.12-alpine

RUN apk add --no-cache --virtual .build-deps \
      musl-dev \
      libffi-dev \
      openssl-dev

RUN pip install --no-cache poetry

WORKDIR /app

RUN mkdir -p data

COPY core/ ./core/
COPY pyproject.toml README.md entrypoint.sh ./
RUN chmod +x entrypoint.sh

RUN poetry lock \
&& poetry config virtualenvs.create false \
&& poetry install --no-interaction --no-ansi \
&& apk del .build-deps 

EXPOSE 8000

CMD ["./entrypoint.sh"]