# Dockerfile.dev
FROM python:3.12-slim AS build-env

RUN pip install --no-cache poetry

WORKDIR /app

RUN mkdir -p data

COPY pyproject.toml poetry.lock README.md ./

RUN poetry config virtualenvs.create false \
&& poetry install --no-root --no-interaction --no-ansi --with dev 

EXPOSE 8000

ENTRYPOINT ["python", "-m", "core.cli"]