# docker-compose.dev.yml
services:
  reverse-proxy-agent:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./reverse_proxy_agent:/app/reverse_proxy_agent
    env_file:
      - .env
    ports:
      - "$PORT:8000"
