# Dockerfile.prod
FROM python:3.12-slim AS build-env

RUN pip install --no-cache poetry

WORKDIR /app

RUN mkdir -p data

COPY firewall_agent/ ./firewall_agent/
COPY pyproject.toml poetry.lock README.md ./

RUN poetry config virtualenvs.create false \
&& poetry install --no-interaction --no-ansi --only main

RUN pip uninstall poetry -y

FROM python:3.12-slim
# FROM gcr.io/distroless/python3

WORKDIR /app

COPY --from=build-env /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=build-env /app /app
ENV PYTHONPATH=/usr/lib/python3.12/site-packages

EXPOSE 8000

ENTRYPOINT ["python", "-m", "firewall_agent.cli", "start"]