# Dockerfile.dev
FROM python:3.12-alpine

RUN apk add --no-cache \
      bash \
      musl-dev \
      libffi-dev \
      openssl-dev

RUN pip install --no-cache poetry

WORKDIR /app
RUN mkdir -p data
COPY pyproject.toml README.md ./


RUN poetry lock \
&& poetry config virtualenvs.create false \
&& poetry install --no-root --no-interaction --no-ansi --with dev

EXPOSE 8000

# CMD ["tail", "-f", "/dev/null"]
CMD ["poetry", "run", "firewall-agent"]