# docker-compose.dev.yml
services:
  firewall-agent:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./firewall_agent:/app/firewall_agent
    env_file:
      - .env
    ports:
      - "$PORT:8000"

    cpus: "0.50"
    mem_limit: 256m    